env:
  PROJECT_PATH: Mifare Classic Tool
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build
      run: ./gradlew assemble
      working-directory: ${{ env.PROJECT_PATH }}
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
